package nbcu.compass.amorttemplate.util;

public enum HeaderEnum {
	AmortTemplateNo,
	AmortTemplateName,
	TitleTypeName,
	FinanceTypeName,
	StraightLineName,
	StraightLineMonths,
	TimePlayName,
	MaxMonths,
	FirstMonthAmortPercent,
	ProjectionScheduleName,
	IsLinkSeries,
	IsMultipleWindowFlag,
	TestUser,
	Username,
	Password,
	TcNo,
	Distributor,
	DealType,
	NegotiatedBy,
	TitleName,
	Window,
	StartDate,
	EndDate,
	RunsInPlayDay,
	RunsPDAllowed,
	LicenseType,
	LicenseAmount,
	AmortSectionNo,
	AmortSectionPercent
}
